### PR TITLE
Incorporate dataset with 300 sims, implement r0 filtering

### LINKED ISSUE #25: Ingest larger dataset with up to 300 simulations
- Decide how to display all simulations in Graph and how to filter on r0
- Ensure on-the-fly Chart quantiles can process all data

### LINKED ISSUE #32: Simulations display incorrectly when r0 is filtered down to 3-4
This could be a result of displaying only 20 simulations so far, but when r0 is filtered down and only 1-2 simulations show, there is some funny business.

### PR DESCRIPTION
**Pull request by lxu213**
Fixes #32. Fixes #25.

### CODE REVIEW

File: .gitignore [hunk 1]
```diff
@@ -16,6 +16,7 @@ launch.json
 # datasets
 /src/store/_archive
 /src/store/sims
+/src/store/model_parameters
```
Comment (BenjiLee) [inline .gitignore:19]: You should probably ignore the whole store folder.

File: src/components/Filters/Brush.js [hunk 2]
```diff
@@ -33,16 +29,16 @@ class Brush extends Component {
...
         ])
         .on('start', this.props.onBrushStart())
         .on('end', this.brushEnded)
         .on('brush', this.brushed)
   }
 
   componentDidMount() {
-    // console.log('componentDidMount')
-    this.setupBrush(this.state.lineGenerator, this.state.series, this.state.dates, this.state.width, this.state.height);
+    console.log('componentDidMount')
```
Comment (BenjiLee) [inline src/components/Filters/Brush.js:40]: I find it helpful to log where this is coming from

`console.log('Brush: componentDidMount')`

File: src/components/Filters/Brush.js [hunk 3]
```diff
@@ -167,22 +153,22 @@ class Brush extends Component {
...
-        // console.log(i, date)
-        // console.log(timeDay.offset(date, -31))
-        // console.log(" ")
-        if (timeYear(date) < timeDay.offset(date, -31)) {
-          return timeFormat('%b')(date);
-        } else {
-          return timeFormat('%Y')(date);
-        }
+        // if (timeYear(date) < timeDay.offset(date, -1)) {
+          return timeFormat('%b-%d')(date);
```
Comment (BenjiLee) [inline src/components/Filters/Brush.js:157]: Depending on how often this format is used, you can extract the format string or make a new function that spits out the desired format. This is mostly for readability and reuse-ability. 

`const monthDateFormat = '%b-%d'`

File: src/components/Graph/MainGraph.js [hunk 4]
```diff
@@ -89,37 +90,50 @@ class MainGraph extends Component {
...
                     newS.vals = s.vals.slice(idxMin, idxMax)
                     return newS
                 })
-                filteredSeriesList.push(filteredSeries)
                 
+                filteredSeriesList.push(filteredSeries)
+                // console.log('on brush change', filteredSeries.map(sim => {return `${sim.name}: ${sim.r0}`}))
+
+                // TODO: may be problematic
+                const percExceedence = simsOver / filteredSeries.length;
```
Comment (BenjiLee) [inline src/components/Graph/MainGraph.js:134]: dunno what JS does when dividing by 0 but you may want to add a defensive check here that you're not trying to divide by 0 if `filteredSeries.length` is null
