### PR TITLE
Fetch fails gracefully with error information

### LINKED ISSUE #142: Failure on fetch should fail gracefully
App should still compile

- [x] Clear fail message - indicate exact model file that is problematic. This may mean adding try catches in `this.initialize` of MainGraph and MainMap

- [x] If geoid file in dropdown doesn't exist, this should also fail gracefully with an alert message to prompt user to select a different geoid and contact the Hopkins team

### PR DESCRIPTION
**Pull request by lxu213**
Fixes #142

### CODE REVIEW

File: src/components/Graph/MainGraph.js [hunk 1]
```diff
@@ -83,87 +83,99 @@ class MainGraph extends Component {
...
+        }
 
-        const r0full = getR0range(dataset, firstScenario, sevList[0], firstIndicator);
-        // seriesListForBrush used by handleBrush to initialize instead of R0 filtering 
-        // series is updated and set to state in scenario, sev, indicator, r0 change handlers
-        const seriesListForBrush = filterR0(
-            r0full, [firstScenario], sevList, firstIndicator, dataset, numDisplaySims);
+        if (Object.keys(dataset).length > 0) {
+            // SCENARIOS: various scenario variables used for a given geoid
+            const SCENARIOS = buildScenarios(dataset);
```
Comment (lxu213) [inline src/components/Graph/MainGraph.js:96]: @BenjiLee is this a janky way to expose errors?

File: src/components/Chart/MainChart.js [hunk 2]
```diff
@@ -54,30 +54,32 @@ class MainChart extends Component {
...
+            this.setState({
+                datasetChart: dataset, 
+                dates,
+                SCENARIOS,
+                scenarioList,
+                scenarioMap,
+                statList,
+                start,
+            }, () => {
+                this.setState({dataLoaded: true});
```
Comment (BenjiLee) [inline src/components/Chart/MainChart.js:80]: note: This is not always going to be set after the previous setState call. It shouldn't matter for this case but it's good to know in case you try to do a setState callback that depends on state.

File: src/components/Graph/MainGraph.js (hunk 1 above)
Comment (BenjiLee) [reply src/components/Graph/MainGraph.js:96]: Sort of. I think you need all of indicators, actuals and dataset. The way you have it now, the code will crash if  you are  missing indicators, actuals but have a dataset. 

You need to check them all to run the logic

Comment (lxu213) [reply src/components/Graph/MainGraph.js]: I think I have addressed this comment with the latest commit.

File: src/components/Chart/MainChart.js (hunk 2 above)
Comment (lxu213) [reply src/components/Chart/MainChart.js:80]: I'm not sure if I've addressed this one? This is in Chart which only depends on `dataset`, so it should be fine?

Comment (BenjiLee) [reply src/components/Chart/MainChart.js:80]: Would just put `dataLoaded` in the original setState and not a callback. Functionally it shouldn't matter but it makes it clearer.

File: src/components/MainContainer.js [hunk 3]
```diff
@@ -42,7 +43,7 @@ class MainContainer extends Component {
 
             this.setState({dataset, actuals, indicators});
         } catch (e) {
-            console.log('Fetch was problematic: ' + e.message)
+            this.setState({fetchErrors: e.message});
         } finally {
             this.setState({dataLoaded: true});
```
Comment (lxu213) [inline src/components/MainContainer.js:48]: @BenjiLee I'm wondering if it's better just to add a catch inside the finally, like so:

```
finally {
   if (Object.keys(dataset).length > 0 && 
            Object.keys(actuals).length > 0 && 
            Object.keys(indicators).length > 0) {

            this.setState({dataLoaded: true});
}
```

Comment (lxu213) [reply src/components/MainContainer.js:48]: That way `dataLoaded` is only flipped on if we know all the data files exists.

Comment (BenjiLee) [reply src/components/MainContainer.js:48]: That can also work.

File: src/components/Map/MainMap.js [hunk 4]
```diff
@@ -212,7 +212,23 @@ class MainMap extends Component {
                             </Fragment>
                             }
                         </Col>
-                    </Row>
+                    </Row>}
+                    {/* Loading finished but indicatorsForCounty is undefined */}
+                    {!isLoading && indicatorsLen === 0 &&
```
Comment (BenjiLee) [inline src/components/Map/MainMap.js:217]: Do `isLoading` and `dataLoaded` serve the same purpose?

File: src/components/Chart/MainChart.js (hunk 2 above)
Comment (lxu213) [reply src/components/Chart/MainChart.js:80]: Oh, so like this instead... I use this callback after previous setState call in all of the containers (MainGraph, MainMap, MainChart, etc) - should they all be changed? You're saying that the callback doesn't even guarantee delayed set state so there's no point in even using one, correct?

``` this.setState({
                scenarios,
                indicators,
                dataLoaded: true
            });
```

Comment (BenjiLee) [reply src/components/Chart/MainChart.js:80]: > You're saying that the callback doesn't even guarantee delayed set state so there's no point in even using one, correct?

Correct. The intention of the code and the result are not the same.

File: src/components/Map/MainMap.js (hunk 4 above)
Comment (lxu213) [reply src/components/Map/MainMap.js:217]: `isLoading` used to indicate if it was still loading (slowly) but basically the same thing. For consistency, I'm going to make it match the other files.

**Comment by veev** [comment]
@lxu213 changed the wording for the chart area. all looks good! feel free to merge
